FROM openjdk:8-alpine
WORKDIR wd
COPY dependencies/ ./
COPY spring-boot-loader/ ./
COPY snapshot-dependencies/ ./
# see https://github.community/t/attempting-to-build-docker-image-with-copy-from-on-actions/16715 and  https://github.com/moby/moby/issues/37965#issuecomment-426853382
RUN true
COPY application/ ./
ENTRYPOINT ["java", "org.springframework.boot.loader.JarLauncher"]
