name: package + build layered + m2 caching
on:
  push:
    branches: [ master ]
env:
  IMAGE_NAME: apcrain/sbcache-layered-layertools-m2-cache

jobs:

  build:
    name: package + build layered + m2 caching
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

      - name: Package .jar
        run: mvn -B clean package

      - name: Extract layers via layertools
        run: java -Djarmode=layertools -jar target/*.jar extract

      - name: Login docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and tag image
        run: >
          DOCKER_BUILDKIT=1
          docker build
          -f Dockerfile.layered-layertools
          --cache-from ${{ env.IMAGE_NAME }}
          -t ${{ env.IMAGE_NAME }}:latest
          -t ${{ env.IMAGE_NAME }}:${{ github.sha }}
          --build-arg BUILDKIT_INLINE_CACHE=1
          .

      - name: Push latest-tagged
        run: docker push ${{ env.IMAGE_NAME }}:latest

      - name: Push sha-tagged
        run: docker push ${{ env.IMAGE_NAME }}:${{ github.sha }}
