name: package and build
on:
  push:
    branches: [ master ]

jobs:

  build:
    name: package + build image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Package .jar
        run: mvn -B clean package

      - name: Unpack .jar
        run: mkdir -p target/unpacked && unzip target/*.jar -d target/unpacked

      - name: Build and push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          cache_froms: apcrain/sbcache:latest
          tag_with_sha: true
          repository: apcrain/sbcache
          tags: latest
