name: package and build
on:
  push:
    branches: [ master ]
env:
  IMAGE_NAME: apcrain/sbcache-fat-jar

jobs:

  build:
    name: package + build fat jar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Package .jar
        run: mvn -B clean package

      - name: Login docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and tag image
        run: >
          docker build
          -f Dockerfile.fat-jar
          -t ${{ env.IMAGE_NAME }}:latest
          -t ${{ env.IMAGE_NAME }}:${{ github.sha }}
          .

      - name: Push latest-tagged
        run: docker push ${{ env.IMAGE_NAME }}:latest

      - name: Push sha-tagged
        run: docker push ${{ env.IMAGE_NAME }}:${{ github.sha }}
