name: package + m2 caching + buildpack
on:
  push:
    branches: [ master ]
env:
  IMAGE_NAME: apcrain/sbcache-buildpack-m2-cache

jobs:

  build:
    name: package + m2 caching + buildpack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

      - name: Package & build via buildpack
        run: mvn -B clean spring-boot:build-image -Dspring-boot.build-image.imageName=${{ env.IMAGE_NAME }}

      - name: Login docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Add sha tag
        run: docker tag ${{ env.IMAGE_NAME }} ${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Push latest-tagged
        run: docker push ${{ env.IMAGE_NAME }}:latest

      - name: Push sha-tagged
        run: docker push ${{ env.IMAGE_NAME }}:${{ github.sha }}
